CREATE TABLE `thinkjs`.`users`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `sex` INT(1) NOT NULL DEFAULT '0',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `confirmtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `statue` INT(1) NOT NULL DEFAULT '0' COMMENT '状态',
  `password` VARCHAR(100) NOT NULL,
  `rid` INT(6) NOT NULL COMMENT '角色',
  `nickname` VARCHAR(20) NOT NULL COMMENT '昵称',
  `mobile` VARCHAR(11) NULL COMMENT '手机号',
  `memo` VARCHAR(100) NULL COMMENT '其他备注信息',
  PRIMARY KEY(`id`),
  INDEX(`mobile`) USING BTREE,
  UNIQUE(`name`)
) ENGINE = InnoDB;